_target_: plbcl_gam.utils.losses.BalancedContrastiveLearning
num_classes: ${dataset.num_classes}
distribution: ${dataset.distribution}
ignore_index: ${dataset.ignore_index}
focal: false
gamma: 2.0
lamb: 1.0
mu: 0.3
temperature: 1.0
in_channels: 64
hidden_d: 512
out_d: 128
max_anchors: 4096
max_context: 32768